name: Deploy to DigitalOcean

on:
  push:
    branches:
      - release

jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Transfer files to DigitalOcean
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.DO_DROPLET_IP }}
        username: root
        key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        source: "./"
        target: "/var/www/splitt-api" # Adjust target directory if needed

    - name: Set environment variables on server
      run: |
        ssh -i ~/.ssh/id_rsa root@${{ secrets.DO_DROPLET_IP }} << EOF
          echo "Setting environment variables..."
          echo "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}" > /var/www/splitt-api/.env
          echo "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}" >> /var/www/splitt-api/.env
          echo "FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }}" >> /var/www/splitt-api/.env
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> /var/www/splitt-api/.env
          echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> /var/www/splitt-api/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> /var/www/splitt-api/.env
          echo "PORT=${{ secrets.PORT }}" >> /var/www/splitt-api/.env
        EOF

    - name: Start the server
      run: |
        ssh -i ~/.ssh/id_rsa root@${{ secrets.DO_DROPLET_IP }} << EOF
          cd /var/www/splitt-api
          pm2 delete splitt-api || true
          pm2 start server.js --name splitt-api --log /var/www/splitt-api/server.log
        EOF

    - name: Wait for server to start
      run: |
        ssh -i ~/.ssh/id_rsa root@${{ secrets.DO_DROPLET_IP }} << EOF
          echo "Waiting for server to start..."
          for i in {1..10}; do
            if grep -q "Server is running on http://localhost:" /var/www/splitt-api/server.log; then
              echo "Server started successfully."
              exit 0
            fi
            sleep 5
          done
          echo "Error: Server did not start."
          cat /var/www/splitt-api/server.log
          exit 1
        EOF
