name: Deploy
on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          port: 22
          envs: JWT_SECRET,JWT_EXPIRES_IN,PORT,FIREBASE_PROJECT_ID,FIREBASE_PRIVATE_KEY_ID,FIREBASE_PRIVATE_KEY,FIREBASE_CLIENT_EMAIL,FIREBASE_CLIENT_ID
          script: |
            set -e
            cd /var/www/splitt-api
            git pull origin release
            npm install

            # Create .env file with proper escaping
            cat > .env << 'EOL'
            JWT_SECRET="${JWT_SECRET}"
            JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
            PORT=${PORT}
            FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID}"
            FIREBASE_PRIVATE_KEY_ID="${FIREBASE_PRIVATE_KEY_ID}"
            FIREBASE_PRIVATE_KEY='${FIREBASE_PRIVATE_KEY}'
            FIREBASE_CLIENT_EMAIL="${FIREBASE_CLIENT_EMAIL}"
            FIREBASE_CLIENT_ID="${FIREBASE_CLIENT_ID}"
            EOL

            pm2 restart splitt-api || pm2 start src/server.js --name splitt-api -- --port 5000
            pm2 save