name: Deploy to DigitalOcean

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/splitt-api
            git pull origin main
            npm install
            
            # Create .env file
            cat > .env << EOL
            JWT_SECRET="${{ secrets.JWT_SECRET }}"
            JWT_EXPIRES_IN="${{ secrets.JWT_EXPIRES_IN }}"
            PORT="5000"
            FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}"
            FIREBASE_PRIVATE_KEY_ID="${{ secrets.FIREBASE_PRIVATE_KEY_ID }}"
            FIREBASE_PRIVATE_KEY='${{ secrets.FIREBASE_PRIVATE_KEY }}'
            FIREBASE_CLIENT_EMAIL="${{ secrets.FIREBASE_CLIENT_EMAIL }}"
            FIREBASE_CLIENT_ID="${{ secrets.FIREBASE_CLIENT_ID }}"
            EOL

            # Restart application
            pm2 restart splitt-api || pm2 start src/server.js --name splitt-api -- --port 5000
            pm2 save

      - name: Health Check
        run: |
          sleep 10
          response=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.DO_DROPLET_IP }}:5000/health)
          if [ "$response" != "200" ]; then
            echo "Deployment failed - Health check returned $response"
            exit 1
          fi