name: Deploy to DigitalOcean

on:
  push:
    branches:
      - release

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: root
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/splitt-api
            git pull origin release
            npm install
            
            # Export environment variables on the server
            echo "export PORT=${{ secrets.PORT }}" >> ~/.bashrc
            echo "export JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ~/.bashrc
            echo "export JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> ~/.bashrc
            echo "export FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> ~/.bashrc
            echo "export FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }}" >> ~/.bashrc
            echo "export FIREBASE_PRIVATE_KEY='${{ secrets.FIREBASE_PRIVATE_KEY }}'" >> ~/.bashrc
            echo "export FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}" >> ~/.bashrc
            echo "export FIREBASE_CLIENT_ID=${{ secrets.FIREBASE_CLIENT_ID }}" >> ~/.bashrc
            source ~/.bashrc

            # Create PM2 ecosystem file with environment variables
            echo "module.exports = {
              apps: [{
                name: 'splitt-api',
                script: 'src/server.js',
                env: {
                  PORT: process.env.PORT,
                  JWT_SECRET: process.env.JWT_SECRET,
                  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
                  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
                  FIREBASE_PRIVATE_KEY_ID: process.env.FIREBASE_PRIVATE_KEY_ID,
                  FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
                  FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
                  FIREBASE_CLIENT_ID: process.env.FIREBASE_CLIENT_ID
                }
              }]
            }" > ecosystem.config.js

            # Restart or start the application using PM2
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
            pm2 save
