name: Test SSH Connection

on:
  push:
    branches:
      - release

jobs:
  test-ssh:
    name: Test SSH Connection
    runs-on: ubuntu-latest

    steps:
      - name: Debug SSH key
        run: |
          echo "SSH Key format check:"
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" | head -n 1
          echo "First and last lines of key:"
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" | head -n 1 && echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" | tail -n 1

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DO_DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -v -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@${{ secrets.DO_DROPLET_IP }} 'echo "SSH Connection Successful"'